.\"	$OpenBSD: syspatch.8,v 1.22 2020/12/07 21:19:28 ajacoutot Exp $
.\"
.\" Copyright (c) 2016 Antoine Jacoutot <ajacoutot@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 5 2026 $
.Dt SYSPATCH 8
.Os
.Sh NAME
.Nm syspatch
.Nd manage base system binary patches
.Sh SYNOPSIS
.Nm syspatch
.Op Fl O
.Op Fl c | l | R | r
.Sh DESCRIPTION
.Nm
is a utility to fetch, verify, install and revert
.Ox
binary patches.
On Appli baseline systems it uses the patches of the running baseline
rather than the official
.Ox
ones:
the baseline number is derived from the release
.Pq Ox 8.0 is baseline 43 ,
patches are fetched from
.Pa blNN/syspatch/<arch>
below the mirror in
.Pa /etc/installurl ,
verified with
.Pa /etc/signify/baseline-NN-syspatch.pub
and named
.Pa blNN-NNN_name .
Kernel patches can only be applied to the Appli kernels
.Pq Dv GENERIC_APPLI.MP No and Dv GENERIC_APPLI.VMM ;
a patch carrying kernel objects but none for the running kernel is refused.
.Pp
When run without any options,
.Nm syspatch
will apply
.Em all
missing patches, creating a rollback tarball containing the files it is about
to replace, then extracting and installing all files contained in the syspatch
tarball.
If any sets are missing, patches are skipped accordingly.
Patches are cumulative and as such it is not possible to install only a subset
of them.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl O
Use the official
.Ox
syspatches instead, fetched directly from
.Lk https://cdn.openbsd.org/pub/OpenBSD/syspatch/ ,
bypassing the mirror, verified with
.Pa /etc/signify/openbsd-XY-syspatch.pub
and named
.Pa XY-NNN_name .
With
.Fl c
this only shows which official patches exist.
Installing them replaces Appli-built files with upstream builds and is
dangerous; it requires typing
.Dq yes
on a terminal.
.It Fl c
List available patches; suitable for
.Xr cron 8 .
.It Fl l
List installed patches.
.It Fl R
Revert all patches.
.It Fl r
Revert the most recently installed patch.
.El
.Sh FILES
.Bl -tag -width "/etc/installurl" -compact
.It Pa /etc/installurl
Mirror top-level URL; Appli patches are fetched from
.Pa blNN/syspatch/<arch>
below it.
.It Pa /etc/signify/baseline-NN-syspatch.pub
Public key used to verify Appli baseline patches.
.It Pa /var/syspatch/*
Directories containing the rollback tarball and the
.Xr diff 1
of installed patches
.Pq Pa blNN-NNN_name No for Appli , Pa XY-NNN_name No for official patches .
.El
.Sh EXIT STATUS
.Ex -std syspatch
In particular, 2 indicates that applying patches was requested but no
additional patch was installed.
.Sh SEE ALSO
.Xr signify 1 ,
.Xr installurl 5 ,
.Xr release 8
.Sh HISTORY
.Nm
first appeared in
.Ox 6.1 .
.Sh AUTHORS
.Nm
was written by
.An Antoine Jacoutot Aq Mt ajacoutot@openbsd.org .
.Sh CAVEATS
.Nm
is designed to work solely on Appli baseline releases and, with
.Fl O ,
official
.Ox
releases.
